apiVersion: batch/v1
kind: Job
metadata:
  name: spark-json-join
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: spark
          image: alhajim/json-join-spark:latest
          imagePullPolicy: Never
          command: ["/opt/bitnami/spark/bin/spark-submit"]
          args:
            - "--master"
            - "local"
            - "--class"
            - "org.example.App"
            - "--conf"
            - "spark.hadoop.fs.s3a.endpoint=http://minio-service:9000"
            - "--conf"
            - "spark.hadoop.fs.s3a.access.key=admin"
            - "--conf"
            - "spark.hadoop.fs.s3a.secret.key=password"
            - "--conf"
            - "spark.hadoop.fs.s3a.path.style.access=true"
            - "--conf"
            - "spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem"
            - "--conf"
            - "spark.hadoop.fs.s3a.connection.ssl.enabled=false"
            - "/opt/bitnami/spark/json-join-spark.jar"
